# exemplo de configuração conexão banco postgree cache

spring.application.name=springCache
spring.datasource.url=jdbc:postgresql://localhost:5432/cache
spring.datasource.username=postgres
spring.datasource.password=1234

#especificar o driver que será utilizado
spring.datasource.driver-class-name=org.postgresql.Driver

#script para popular o banco de dados:
spring.sql.init.data-locations=classpath:script.sql

spring.jpa.show-sql=true


# passar para o redis (dados de exemplo)

#pode se colocar o redis para rodar na propria maquina (utilizar um docker-- redis)

spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.cache.type=redis